### ISSUE TITLE
Bad aggregate signature

### ISSUE THREAD

**Issue by matholamew** [xch-gallery/nft-companion#10]
I have everything setup correctly, I think, but I am getting an error when submitting the transaction. I have the testnet10 setup, some test XCH, and no errors up until submitting. fwiw: I am running on a M1 Mac.

Can anyone offer any help?

Failed to submit NFT: {"detail":"Failed to include transaction 'transaction###', error BAD_AGGREGATE_SIGNATURE", "success":false}}

**Comment by greimela** [comment]
I think we solved this issue via Discord.
The reason was that the wallet unexpectedly connected to mainnet.
