### ISSUE TITLE
Can't select amount higher than our spendable balance

### ISSUE THREAD

**Issue by syntheticperson** [xch-gallery/nft-companion#7]
I created a wallet using these instructions:
https://xch.gallery/help/install-wallet

Then I installed nft-companion following these instructions:
https://github.com/xch-gallery/nft-companion

When I try to create an NFT, I get the error "Can't select amount higher than our spendable balance"

Please find attached error log.
What am I missing?

If my wallet requires a balance in order to generate an NFT, how do I send XCH to a wallet on testnet?

Thanks

[NFT_SpendableBalanceError.txt](https://github.com/xch-gallery/nft-companion/files/8148173/NFT_SpendableBalanceError.txt)

**Comment by greimela** [comment]
Yes, you are right, you currently need 1023 mojos to create an NFT.
This is because a normal TXCH coin has to be converted in that process.

You can get some TXCH from the official faucet: https://testnet10-faucet.chia.net/

**Comment by syntheticperson** [comment]
Good to know.
Thanks
